apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: traffic-config-propagation
  namespace: tf-monitor
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: traffic-config
    - apiVersion: v1
      kind: Secret
      name: traffic-secret
  placement:
    clusterAffinity:
      clusterNames:
        - cp-plugfest-member1
        - cp-plugfest-member2
